services:
  - type: web
    name: my-ajax-project
    repo: https://github.com/zmyslek/ok
    branch: main
    dockerfilePath: Dockerfile
    buildCommand: ""
    startCommand: php artisan serve --host 0.0.0.0 --port $PORT
    runtime: docker
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        value: base64:your_app_key_here
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        value: your_database_host
      - key: DB_PORT
        value: 3306
      - key: DB_DATABASE
        value: your_database_name
      - key: DB_USERNAME
        value: your_database_user
      - key: DB_PASSWORD
        value: your_database_password
